name: cicd
on:
  workflow_dispatch: null
      inputs:
          environments:
              description: This the environment that is Bydefault dev 
              default: 'dev' 
              required: true 
              type: choice 
              options: 
                  - dev
                  - staging 
                  - prod
  
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Code Clone from Github"
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Build the Docker Container"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the Code
        run: echo "Testing the Code"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the code
        run: echo "Deployed"
