name: cicd
on:
  workflow_dispatch: null
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Code Clone from Github"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Build the Docker Container"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the Code
        run: echo "Testing the Code"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the code
        run: echo "Deployed"
