name: Portfolio Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
    deploy:

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure GitHub Pages
              uses: actions/configure-pages@v4

            - name: Build and upload artifact
              run: actions/upload-pages-artifact@v4

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
         
                